version: "3.9"
services:
  servidor_principal:
    build: .
    ports:
      - "4000:8000"
    links:
      - servidor_secundario
  servidor_secundario:
    image: node:12.16.1-alpine
    ports:
      - "4001:8000"